version: '2'
services:

  caddy:
    image: abiosoft/caddy:latest
    container_name: caddy
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
      - 2015:2015
    volumes:
      - caddy:/etc/caddy
      - /home/pcampbell/Docker/Jenkins/caddy/Caddyfile:/etc/Caddyfile
    networks:
      - proxy
    environment:
      CADDYPATH: /etc/caddy
      ACME_AGREE: "true"

  jenkins:
    build: jenkins/
    container_name: jenkins
    restart: unless-stopped
    ports:
      - 8080:8080
    volumes:
      - jenkins_home:/var/jenkins_home
      - /home/pcampbell:/home/pcampbell
    networks:
      - jenkins
      - jenkins-mail
      - proxy
    environment:
      VIRTUAL_HOST: jenkins.kemitix.net
  
  mailserver:
    image: mailhog/mailhog
    container_name: mail
    ports:
      - 1025:1025
      - 8025:8025
    restart: unless-stopped
    networks:
      - jenkins-mail

  nexus:
    build: nexus/
    container_name: nexus
    ports:
      - 9080:8081
    restart: unless-stopped
    volumes:
      - nexus:/sonatype-work
    networks:
      - jenkins

  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: reverse-proxy
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - proxy

  squid:
    #image: sameersbn/squid
    build: squid
    container_name: proxy
    restart: unless-stopped
    ports:
      - 3128:3128
    volumes:
      - squid_cache:/var/spool/squid3
      - ./squid/squid.conf:/etc/squid3/squid.conf

networks:
  jenkins:
  jenkins-mail:
  proxy:

volumes:
  jenkins_home:
  nexus:
  squid_cache:
  caddy:
