version: '2'
services:

  jenkins:
    #image: jenkins/jenkins:latest
    build: jenkins/
    container_name: jenkins
    restart: unless-stopped
    ports:
      - 9090:8080
      - 50000:50000
      - 9091:9091
    volumes:
#- /home/pcampbell/Volumes/JenkinsHome:/var/jenkins_home
      - jenkins_home:/var/jenkins_home
      - /home/pcampbell:/home/pcampbell
    networks:
      - jenkins

  sonarqube:
    image: sonarqube
    container_name: sonarqube
    restart: unless-stopped
    ports:
      - 9000:9000
    environment:
      - SONARQUBE_JDBC_URL=jdbc:postgresql://db:5432/sonar
    volumes:
      - sonarqube_conf:/opt/sonarqube/conf
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_bundled-plugins:/opt/sonarqube/lib/bundled-plugins
    networks:
      - jenkins

  db:
    image: postgres
    container_name: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
    volumes:
      - postgresql:/var/lib/postgresql
      - postgresql_data:/var/lib/postgresql/data
    networks:
      - jenkins

  mailserver:
    image: mailhog/mailhog
    container_name: mail
    ports:
      - 1025:1025
      - 8025:8025
    restart: unless-stopped
    networks:
      - jenkins

  nexus:
    #image: sonatype/nexus
    build: nexus/
    container_name: nexus
    ports:
      - 9080:8081
    restart: unless-stopped
    volumes:
      - nexus:/sonatype-work
    networks:
      - jenkins

networks:
  jenkins:
    driver: bridge

volumes:
  jenkins_home:
  sonarqube_conf:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_bundled-plugins:
  postgresql:
  postgresql_data:
  nexus:
