version: '2'
services:

  jenkins:
    build: jenkins/
    container_name: jenkins
    restart: unless-stopped
    expose:
      - 8080
    volumes:
      - jenkins_home:/var/jenkins_home
      - /home/pcampbell:/home/pcampbell
    networks:
      - jenkins
      - jenkins-mail
      - proxy
    environment:
      VIRTUAL_HOST: jenkins.kemitix.net
  
  sonarqube:
    image: sonarqube
    container_name: sonarqube
    restart: unless-stopped
    expose:
      - 9000
    environment:
      SONARQUBE_JDBC_URL: jdbc:postgresql://db:5432/sonar
      VIRTUAL_HOST: sonarqube.kemitix.net
    volumes:
      - sonarqube_conf:/opt/sonarqube/conf
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_bundled-plugins:/opt/sonarqube/lib/bundled-plugins
    networks:
      - jenkins
      - jenkins-mail
      - proxy
      - sonar-db

  db:
    image: postgres
    container_name: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
    volumes:
      - postgresql:/var/lib/postgresql
      - postgresql_data:/var/lib/postgresql/data
    networks:
      - sonar-db

  mailserver:
    image: mailhog/mailhog
    container_name: mail
    ports:
      - 1025:1025
      - 8025:8025
    restart: unless-stopped
    networks:
      - jenkins-mail

  nexus:
    build: nexus/
    container_name: nexus
    ports:
      - 9080:8081
    restart: unless-stopped
    volumes:
      - nexus:/sonatype-work
    networks:
      - jenkins

  nginx-proxy:
    image: jwilder/nginx-proxy
    #build: reverse-proxy/nginx-proxy
    container_name: reverse-proxy
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - proxy

  squid:
    image: sameersbn/squid:3.3.8-23
    container_name: proxy
    restart: unless-stopped
    ports:
      - 3128:3128
    volumes:
      - squid_cache:/var/spool/squid3
      - ./squid/squid.conf:/etc/squid3/squid.conf

networks:
  jenkins:
  jenkins-mail:
  sonar-db:
  proxy:

volumes:
  jenkins_home:
  sonarqube_conf:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_bundled-plugins:
  postgresql:
  postgresql_data:
  nexus:
  squid_cache:
