version: '2'
services:
    jenkins:
        #image: jenkins/jenkins:latest
        build: .
        container_name: jenkins
        ports:
              - '9090:8080'
              - '50000:50000'
        volumes:
             - /home/pcampbell/Volumes/JenkinsHome:/var/jenkins_home
        
